In [2]:
import numpy as np

In [5]:
np.zeros(100)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
np.zeros(5)+2

array([2., 2., 2., 2., 2.])

In [7]:
np.zeros(5)*2

array([0., 0., 0., 0., 0.])

In [11]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [12]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [14]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

identity matrix

In [15]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### random no 0 & 1

In [16]:
np.random.rand(10)

array([0.80374451, 0.55848011, 0.53553634, 0.20839837, 0.31903421,
       0.74918543, 0.88659346, 0.69289538, 0.42689717, 0.893785  ])

In [17]:
np.random.rand()

0.6332754045658485

[link text](https://)

standard normal distributation

In [20]:
np.random.randn(25)

array([ 0.87411465,  1.98111445,  1.10702374, -0.56866086,  0.90374132,
        1.39685804,  2.19541561, -0.86359761, -1.67747499,  0.84806067,
       -1.88306932,  0.23948641,  1.2099331 ,  0.95423523,  0.81298052,
        0.40050291, -0.10768368, -1.18482693, -0.43766382, -1.6675716 ,
       -0.02559974,  0.09235967,  0.81456796, -1.41206467, -0.39551412])

In [21]:
np.random.rand(25)

array([0.45434938, 0.93531788, 0.66839814, 0.47079086, 0.67733899,
       0.38701857, 0.69008968, 0.20570542, 0.90394069, 0.12749455,
       0.79374134, 0.52767229, 0.17680637, 0.3906094 , 0.28828409,
       0.00677977, 0.96733469, 0.71872151, 0.82265187, 0.87432802,
       0.82982936, 0.69632072, 0.68736017, 0.89607708, 0.13936463])

In [22]:
np.random.randn(100)

array([-1.93974364,  0.15469255,  0.37561802, -0.19778597,  2.2075807 ,
        0.11386872, -1.33557846, -0.31556188, -0.90418641, -0.71906056,
       -0.14155706, -0.13849033, -0.12675151, -0.87462479, -0.83262999,
        0.40943511, -0.02320051,  0.32542418,  0.23653713,  0.13064028,
       -2.21931749, -1.39121258,  0.43004369, -0.69154005,  1.09687151,
       -0.64603637,  1.38949853, -0.12801314, -0.83586765,  1.62302961,
       -0.23547735, -0.81955767, -0.41691905, -0.43749128, -0.81780758,
       -0.64169716,  1.1727121 , -1.11808942, -0.49461609,  1.71148099,
        0.09150445,  1.1234165 ,  0.1968634 , -0.20475112,  1.6342317 ,
        0.21013285, -1.01194315, -0.86130851, -0.62983723, -1.80505007,
       -0.5958997 , -1.09166522,  0.34435268,  1.20053573, -0.52808715,
       -1.08540315,  0.20516227,  0.8392807 , -1.52741313, -1.14464165,
        0.36832577,  0.33090662, -0.65006063, -2.17734867,  1.0441359 ,
        1.9350328 ,  0.23877019,  0.96558319, -0.93049564,  0.54

In [33]:
np.arange(0.01,1.01,0.01).reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [35]:
np.linspace(1,100,100).reshape(10,10)/100

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

create an array of 20 linear spaced points betn 0 & 1

In [39]:
arr=np.arange(1,26).reshape(5,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [40]:
arr.sum()

325

In [49]:
np.sum(arr,axis=1)

array([ 15,  40,  65,  90, 115])